create table
    public.studio (
                      id bigint generated by default as identity not null,
                      key character varying null,
                      value text null,
                      createdat timestamp with time zone not null default now(),
                      constraint studio_pkey primary key (id)
) tablespace pg_default;

create table
    public.designs (
                       id uuid not null default gen_random_uuid (),
                       "externalId" bigint null,
                       "sourceImageId" bigint null unique,
                       sha256 text null unique check (sha256 ~ '^[0-9a-f]{64}$'),
                       source text null,
                       title character varying not null,
                       slug character varying null,
                       description text not null,
                       keywords text not null,
                       "imageName" character varying null,
                       "externalImageUrl" text null,
                       "externalLink" text null,
                       category character varying null default 'no_category'::character varying,
                       collection character varying null default 'no_collection'::character varying,
                       "backgroundColor" character varying not null default '#FFFFFF'::character varying,
                       "backgroundColors" text null,
                       shared boolean null default false,
                       props json null,
                       "createdAt" timestamp with time zone not null default now(),
                       "updatedAt" timestamp without time zone null,
                       constraint designs_pkey primary key (id),
                       constraint designs_externalid_key unique ("externalId"),
                       constraint designs_title_key unique (title),
                       constraint designs_slug_key unique (slug)
) tablespace pg_default;

create table
    public.collections (
                       id uuid not null default gen_random_uuid (),
                       "externalId" bigint not null,
                       title character varying not null,
                       description text null,
                       "coverImageUrl" text null,
                       "createdAt" timestamp with time zone not null default now(),
                       "updatedAt" timestamp without time zone null,
                       constraint collections_pkey primary key (id),
                       constraint collections_externalid_key unique ("externalId")
) tablespace pg_default;

create table
    public.design_collections (
                       "designId" uuid not null references public.designs (id) on delete cascade,
                       "collectionId" uuid not null references public.collections (id) on delete cascade,
                       constraint design_collections_pkey primary key ("designId", "collectionId")
) tablespace pg_default;

create index if not exists design_collections_collectionid_idx on public.design_collections ("collectionId");

ALTER TABLE public.studio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Studio" ON public.studio FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public Read Designs" ON public.designs FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public Read Collections" ON public.collections FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public Read Design Collections" ON public.design_collections FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Service Role Studio All" ON public.studio FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Designs All" ON public.designs FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Collections All" ON public.collections FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Design Collections All" ON public.design_collections FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE TABLE IF NOT EXISTS public.design_listings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "designId" UUID NOT NULL REFERENCES public.designs(id) ON DELETE CASCADE,
  platform TEXT NOT NULL CHECK (platform IN ('redbubble', 'teepublic', 'spreadshirt')),
  account TEXT NOT NULL,
  "externalId" TEXT NOT NULL,
  url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  tags JSONB,
  "thumbnailUrl" TEXT,
  "publishedAt" TIMESTAMPTZ,
  extra JSONB,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (platform, "externalId"),
  UNIQUE ("designId", platform, account)
);

ALTER TABLE public.design_listings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.design_listings FROM anon, authenticated;
GRANT SELECT ("designId", platform, "externalId", url) ON public.design_listings TO anon, authenticated;
GRANT ALL ON public.design_listings TO service_role;

CREATE POLICY "Service Role Listings All" ON public.design_listings FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Listing Links" ON public.design_listings FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.design_social_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "designId" UUID NOT NULL REFERENCES public.designs(id) ON DELETE CASCADE,
  channel TEXT NOT NULL CHECK (channel IN ('pinterest', 'bluesky', 'mastodon', 'instagram', 'threads', 'reddit', 'tiktok', 'youtube', 'x', 'linkedin')),
  account TEXT NOT NULL CHECK (char_length(account) <= 100),
  variant TEXT NOT NULL CHECK (char_length(variant) <= 50),
  "externalId" TEXT NOT NULL CHECK (char_length("externalId") <= 200),
  url TEXT NOT NULL CHECK (char_length(url) <= 2000),
  "linkUrl" TEXT,
  title TEXT CHECK (char_length(title) <= 500),
  caption TEXT CHECK (char_length(caption) <= 5000),
  hashtags JSONB,
  "imageUrl" TEXT,
  board TEXT CHECK (char_length(board) <= 200),
  status TEXT NOT NULL CHECK (status IN ('published', 'removed')),
  "publishedAt" TIMESTAMPTZ NOT NULL,
  "removedAt" TIMESTAMPTZ,
  extra JSONB,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT design_social_posts_removed_check CHECK (status <> 'removed' OR "removedAt" IS NOT NULL),
  UNIQUE (channel, "externalId"),
  UNIQUE ("designId", channel, account, variant)
);
CREATE INDEX IF NOT EXISTS design_social_posts_designid_idx ON public.design_social_posts ("designId");
CREATE INDEX IF NOT EXISTS design_social_posts_channel_publishedat_idx ON public.design_social_posts (channel, "publishedAt");
CREATE INDEX IF NOT EXISTS design_social_posts_account_publishedat_idx ON public.design_social_posts (account, "publishedAt");
CREATE INDEX IF NOT EXISTS design_social_posts_status_idx ON public.design_social_posts (status);

ALTER TABLE public.design_social_posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.design_social_posts FROM anon, authenticated;
GRANT ALL ON public.design_social_posts TO service_role;

CREATE POLICY "Service Role Social Posts All" ON public.design_social_posts FOR ALL TO service_role USING (true) WITH CHECK (true);
