create table
    public.studio (
                      id bigint generated by default as identity not null,
                      key character varying null,
                      value text null,
                      createdat timestamp with time zone not null default now(),
                      constraint studio_pkey primary key (id)
) tablespace pg_default;

create table
    public.designs (
                       id uuid not null default gen_random_uuid (),
                       "externalId" bigint not null,
                       title character varying not null,
                       description text not null,
                       keywords text not null,
                       "imageName" character varying null,
                       "externalImageUrl" text null,
                       "externalLink" text null,
                       category character varying null default 'no_category'::character varying,
                       collection character varying null default 'no_collection'::character varying,
                       "backgroundColor" character varying not null default '#FFFFFF'::character varying,
                       "backgroundColors" text null,
                       shared boolean null default false,
                       props json null,
                       "createdAt" timestamp with time zone not null default now(),
                       "updatedAt" timestamp without time zone null,
                       constraint designs_pkey primary key (id),
                       constraint designs_externalid_key unique ("externalId"),
                       constraint designs_title_key unique (title)
) tablespace pg_default;

ALTER TABLE public.studio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.designs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Studio" ON public.studio FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public Read Designs" ON public.designs FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Service Role Studio All" ON public.studio FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Designs All" ON public.designs FOR ALL TO service_role USING (true) WITH CHECK (true);